env:
  node: true
  es2021: true
extends: standard-with-typescript
overrides: []
parserOptions:
  project:
    - './tsconfig.json'
  ecmaVersion: latest
  sourceType: module
plugins:
  - 'eslint-plugin-tsdoc'
rules: {
  '@typescript-eslint/space-before-function-paren': 'off',
  '@typescript-eslint/strict-boolean-expressions': 'off',
  'tsdoc/syntax': 'warn'
}
